site_name: "Raktar"
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    primary: custom
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_css:
  - stylesheets/extra.css
nav:
  - "Backend Installation":
    - "Pre-requisites": "backend/pre-requisites.md"
    - "Manual Steps": "backend/manual-steps.md"
    - "CDK Deployment": "backend/cdk-deployment.md"
    - "SSO Application Configuration": "backend/sso-app-setup.md"
  - "Frontend Installation":
    - "Pre-requisites": "frontend/pre-requisites.md"
    - "Installation": "frontend/installation.md"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
